<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Docente;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
    public function run()
    {

        $admin = User::create([
            'cedula' => '0201234567',
            'nombres' => 'ADMINISTRADOR',
            'apellidos' => 'ADMINISTRADOR',
            'email' => 'admin@libertador.edu.ec',
            'password' => Hash::make('password'),
            'tipo_usuario' => 'administrador',
            'telefono' => '0999999999',
            'activo' => true,
        ]);

        $admin->assignRole('administrador');
        // Lista de docentes extraídos del CSV
        $docentes = [
            [
                'cedula' => '0201641792',
                'nombres' => 'DIANA MAGALI',
                'apellidos' => 'ALEGRIA CAMINO',
                'email' => 'diana.alegria@libertador.edu.ec',
                'telefono' => '0987654321',
                'titulo_profesional' => 'MAGISTER EN SISTEMAS DE INFORMACION MENCIÓN EN INTELIGENCIA DE NEGOCIOS Y ANALÍTICA DE DATOS MASIVOS, LICENCIADA EN CIENCIAS DE LA EDUCACIÓN MENCIÓN INFORMÁTICA EDUCATIVA',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2015-02-03',
                'activo' => true,
            ],
            [
                'cedula' => '0201851235',
                'nombres' => 'DIANA',
                'apellidos' => 'DEL SALTO VASCONEZ',
                'email' => 'diana.delsalto@libertador.edu.ec',
                'telefono' => '0987654323',
                'titulo_profesional' => 'MAGISTER EN EDUCACIÓN BÁSICA, LICENCIADA EN CIENCIAS DE LA EDUCACION MENCIÓN INGLÉS',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2017-01-06',
                'activo' => true,
            ],
            [
                'cedula' => '0201794054',
                'nombres' => 'CRISTOPHER DANILO',
                'apellidos' => 'ALLAN GRANJA',
                'email' => 'cristopher.allan@libertador.edu.ec',
                'telefono' => '0987654324',
                'titulo_profesional' => 'ING. AGRÓNOMO',
                'grado_ocupacional' => 'SP3',
                'modalidad_trabajo' => 'MT',
                'fecha_vinculacion' => '2017-01-11',
                'activo' => true,
            ],
            [
                'cedula' => '0201767845',
                'nombres' => 'SANDRO BLADIMIR',
                'apellidos' => 'CHAMORRO CORDOVA',
                'email' => 'sandro.chamorro@libertador.edu.ec',
                'telefono' => '0987654325',
                'titulo_profesional' => 'INGENIERO AGROPECUARIO INDUSTRIAL',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => null,
                'fecha_vinculacion' => '2014-10-15',
                'activo' => false, // SIN CARGA HORARIA
            ],
            [
                'cedula' => '0201017266',
                'nombres' => 'LUIS ORLANDO',
                'apellidos' => 'CRUZ GOMEZ',
                'email' => 'luis.cruz@libertador.edu.ec',
                'telefono' => '0987654326',
                'titulo_profesional' => 'DOCTOR EN MEDICINA VETERINARIA Y ZOOTECNIA',
                'grado_ocupacional' => 'SP3',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2018-01-07',
                'activo' => true,
            ],
            [
                'cedula' => '0201983152',
                'nombres' => 'ALEXIS MARIBEL',
                'apellidos' => 'FIERRO MONTERO',
                'email' => 'alexis.fierro@libertador.edu.ec',
                'telefono' => '0987654327',
                'titulo_profesional' => 'MAGISTER EN CIBERSEGURIDAD, INGENIERA EN SISTEMAS COMPUTACIONALES',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2014-10-15',
                'activo' => true,
            ],
            [
                'cedula' => '0201580016',
                'nombres' => 'ALEX FABIAN',
                'apellidos' => 'GALARZA LUNA',
                'email' => 'alex.galarza@libertador.edu.ec',
                'telefono' => '0987654328',
                'titulo_profesional' => 'MAGISTER EN PEDAGOGÍA MENCIÓN EN EDUCACIÓN TECNICA Y TECNOLÓGICA, DIPLOMA SUPERIOR EN PROYECTOS DE INVESTIGACION SOCIAL, ABOGADO DE LOS TRIBUNALES Y JUZGADOS DE LA REPUBLICA, LICENCIADO EN CIENCIAS DE LA EDUCACION MENCIÓN INFORMÁTICA EDUCATIVA',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2014-10-15',
                'activo' => true,
            ],
            [
                'cedula' => '1207750389',
                'nombres' => 'HENRRY JOSUE',
                'apellidos' => 'MARIÑO ACOSTA',
                'email' => 'henrry.mariño@libertador.edu.ec',
                'telefono' => '0987654329',
                'titulo_profesional' => 'MAGISTER EN CIBERSEGURIDAD, INGENIERO EN SISTEMAS',
                'grado_ocupacional' => 'SP2',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2018-01-11',
                'activo' => true,
            ],
            [
                'cedula' => '0201726726',
                'nombres' => 'ALVARO VINICIO',
                'apellidos' => 'MOREJON VALVERDE',
                'email' => 'alvaro.morejon@libertador.edu.ec',
                'telefono' => '0987654330',
                'titulo_profesional' => 'MEDICO VETERINARIO Y ZOOTECNISTA',
                'grado_ocupacional' => 'SP3',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2021-01-12',
                'activo' => true,
            ],
            [
                'cedula' => '0919118331',
                'nombres' => 'MARIA ELENA',
                'apellidos' => 'NAVARRETE VINCES',
                'email' => 'maria.navarrete@libertador.edu.ec',
                'telefono' => '0987654331',
                'titulo_profesional' => 'MAGISTER EN SISTEMAS DE INFORMACIÓN GERENCIAL, LICENCIADO EN SISTEMAS DE INFORMACIÓN GERENCIAL',
                'grado_ocupacional' => 'SP2',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2020-01-12',
                'activo' => true,
            ],
            [
                'cedula' => '0201790185',
                'nombres' => 'EDWIN ELADIO',
                'apellidos' => 'PAUCAR CORNELIO',
                'email' => 'edwin.paucar@libertador.edu.ec',
                'telefono' => '0987654332',
                'titulo_profesional' => 'ING. AGRÓNOMO, MSC. EN AGROECOLOGÍA Y AGRICULTURA SOSTENIBLE',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2014-01-11',
                'activo' => true,
            ],
            [
                'cedula' => '0201890886',
                'nombres' => 'DIANA ANAID',
                'apellidos' => 'RAMIREZ GARÓFALO',
                'email' => 'diana.ramirez@libertador.edu.ec',
                'telefono' => '0987654333',
                'titulo_profesional' => 'MAGISTER EN CIBERSEGURIDAD, INGENIERA EN INFORMÁTICA, TECNOLOGA EN INFORMÁTICA APLICADA',
                'grado_ocupacional' => 'SP3',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2018-01-12',
                'activo' => true,
            ],
            [
                'cedula' => '0201835436',
                'nombres' => 'ROSARIO JAJAIRA',
                'apellidos' => 'SALAZAR GUERRERO',
                'email' => 'rosario.salazar@libertador.edu.ec',
                'telefono' => '0987654334',
                'titulo_profesional' => 'INGENIERA EN CONTABILIDAD Y AUDITORIA CPA',
                'grado_ocupacional' => 'SP3',
                'modalidad_trabajo' => 'MT',
                'fecha_vinculacion' => '2017-01-06',
                'activo' => true,
            ],
            [
                'cedula' => '0202080263',
                'nombres' => 'WILSON GABRIEL',
                'apellidos' => 'AGUALONGO AMANGANDI',
                'email' => 'wilson.agualongo@libertador.edu.ec',
                'telefono' => '0987654335',
                'titulo_profesional' => 'MAGISTER EN ELECTROMECÁNICA, INGENIERO AUTOMOTRIZ',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'MT',
                'fecha_vinculacion' => '2018-01-11',
                'activo' => true,
            ],
            [
                'cedula' => '0202305140',
                'nombres' => 'BYRON DARIO',
                'apellidos' => 'ANALUIZA HIDALGO',
                'email' => 'byron.analuiza@libertador.edu.ec',
                'telefono' => '0987654336',
                'titulo_profesional' => 'MAGISTER EN DISEÑO INDUSTRIAL Y PROCESOS, INGENIERO AUTOMOTRIZ',
                'grado_ocupacional' => 'SP3',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2018-01-11',
                'activo' => true,
            ],
            [
                'cedula' => '1803781317',
                'nombres' => 'JAIME ANGEL',
                'apellidos' => 'ARMENDARIZ JEREZ',
                'email' => 'jaime.armendariz@libertador.edu.ec',
                'telefono' => '0987654337',
                'titulo_profesional' => 'INGENIERO EN ELECTRONICA E INSTRUMENTACION, MASTER UNIVERSITARIO EN TECNOLOGIA EDUCATIVA Y COMPETENCIAS DIGITALES',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2022-01-12',
                'activo' => true,
            ],
            [
                'cedula' => '0201785599',
                'nombres' => 'ROMMEL ALEXIS',
                'apellidos' => 'BARRAGAN LLANOS',
                'email' => 'rommel.barragan@libertador.edu.ec',
                'telefono' => '0987654338',
                'titulo_profesional' => 'MAGISTER EN ECOEFICIENCIA INDUSTRIAL MENCIÓN EN EFICIENCIA ENERGETICA, INGENIERO EN ADMINISTRACIÓN Y PRODUCCIÓN INDUSTRIAL, TECNÓLOGO EN ELECTRICIDAD',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2019-01-11',
                'activo' => true,
            ],
            [
                'cedula' => '0202046793',
                'nombres' => 'WILLAM PATRICIO',
                'apellidos' => 'CAÑAR YUMBOLEMA',
                'email' => 'willam.cañar@libertador.edu.ec',
                'telefono' => '0987654339',
                'titulo_profesional' => 'MAGISTER EN ELECTRÓNICA Y AUTOMATIZACIÓN MENCIÓN CONTROL DE PROCESOS, INGENIERO EN ELECTRÓNICA CONTROL Y REDES INDUSTRIALES',
                'grado_ocupacional' => 'SP2',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2017-01-07',
                'activo' => true,
            ],
            [
                'cedula' => '0201053063',
                'nombres' => 'JOSE NAPOLEON',
                'apellidos' => 'CHAVEZ CARDENAS',
                'email' => 'jose.chavez@libertador.edu.ec',
                'telefono' => '0987654340',
                'titulo_profesional' => 'LICENCIADO EN CIENCIAS DE LA EDUCACIÓN, PROFESOR DE ENSEÑANZA MEDIA EN EDUCACIÓN TÉCNICA ESPECIALIDAD: ELECTRICIDAD, DOCTOR EN CIENCIAS DE LA EDUCACIÓN MENCIÓN ADMINISTRACIÓN EDUCATIVA',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2018-01-07',
                'activo' => true,
            ],
            [
                'cedula' => '1203172166',
                'nombres' => 'ZOILA MARIA',
                'apellidos' => 'GALEAS PESANTES',
                'email' => 'zoila.galeas@libertador.edu.ec',
                'telefono' => '0987654341',
                'titulo_profesional' => 'MAGISTER EN GESTIÓN EDUCATIVA, LICENCIADO EN CIENCIAS DE LA EDUCACIÓN ESPECIALIZACIÓN FÍSICO MATEMÁTICAS',
                'grado_ocupacional' => 'SP2',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2018-01-07',
                'activo' => true,
            ],
            [
                'cedula' => '0201762762',
                'nombres' => 'JHONY POLIBIO',
                'apellidos' => 'POZO CHAVES',
                'email' => 'jhony.pozo@libertador.edu.ec',
                'telefono' => '0987654342',
                'titulo_profesional' => 'MAGISTER EN MANUFACTURA Y DISEÑO ASISTIDO POR COMPUTADOR, INGENIERO AUTOMOTRIZ, DIPLOMADO SUPERIOR EN AUTOTRÓNICA',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2019-01-11',
                'activo' => true,
            ],
            [
                'cedula' => '0200859585',
                'nombres' => 'ANGELITO GUILLERMO',
                'apellidos' => 'REMACHE AGUALONGO',
                'email' => 'angelito.remache@libertador.edu.ec',
                'telefono' => '0987654343',
                'titulo_profesional' => 'LICENCIADO EN CIENCIAS DE LA EDUCACION MENCION FISICA Y MATEMATICA, LICENCIADO EN CIENCIAS DE LA EDUCACIÓN MENCIÓN INFORMÁTICA EDUCATIVA, INGENIERO COMERCIAL',
                'grado_ocupacional' => 'SP3',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2017-01-11',
                'activo' => true,
            ],
            [
                'cedula' => '0503165474',
                'nombres' => 'MILTON XAVIER',
                'apellidos' => 'REMACHE SASIG',
                'email' => 'milton.remache@libertador.edu.ec',
                'telefono' => '0987654344',
                'titulo_profesional' => 'MAGISTER EN SEGURIDAD Y PREVENCION DE RIESGOS DEL TRABAJO, MAGISTER EN ELECTROMECÁNICA, INGENIERO EN ELECTROMECANICA',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2021-01-12',
                'activo' => true,
            ],
            [
                'cedula' => '0201534252',
                'nombres' => 'JORGE ALFREDO',
                'apellidos' => 'RIOS ENCALADA',
                'email' => 'jorge.rios@libertador.edu.ec',
                'telefono' => '0987654345',
                'titulo_profesional' => 'MAGISTER EN ECOEFICIENCIA INDUSTRIAL MENCIÓN EFICIENCIA ENERGÉTICA, INGENIERO EN ADMINISTRACIÓN Y PRODUCCIÓN INDUSTRIAL, TECNÓLOGO EN ELECTRÓNICA, LICENCIADO EN CIENCIAS DE LA EDUCACIÓN MENCIÓN INFORMÁTICA EDUCATIVA',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2014-10-15',
                'activo' => true,
            ],
            [
                'cedula' => '0202344206',
                'nombres' => 'ESTALIN JAVIER',
                'apellidos' => 'SALTOS TAIPE',
                'email' => 'estalin.saltos@libertador.edu.ec',
                'telefono' => '0987654346',
                'titulo_profesional' => 'INGENIERO EN ELECTRÓNICA, TELECOMUNICACIONES Y REDES',
                'grado_ocupacional' => 'SP3',
                'modalidad_trabajo' => 'MT',
                'fecha_vinculacion' => '2022-01-07',
                'activo' => true,
            ],
            [
                'cedula' => '0201736683',
                'nombres' => 'VERÓNICA ELIZABETH',
                'apellidos' => 'SÁNCHEZ AGUIAR',
                'email' => 'veronica.sanchez@libertador.edu.ec',
                'telefono' => '0987654347',
                'titulo_profesional' => 'LICENCIADA EN CIENCIAS DE LA EDUCACIÓN MENCIÓN INFORMÁTICA',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2014-10-15',
                'activo' => true,
            ],
            [
                'cedula' => '0502924822',
                'nombres' => 'PAOLA BELEN',
                'apellidos' => 'SEGOVIA TOSCANO',
                'email' => 'paola.segovia@libertador.edu.ec',
                'telefono' => '0987654348',
                'titulo_profesional' => 'MASTER EN DISEÑO Y GESTION DE PROYECTOS TECNOLOGICOS, INGENIERA EN ELECTRONICA Y COMUNICACIONES',
                'grado_ocupacional' => 'SP3',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2021-01-12',
                'activo' => true,
            ],
            [
                'cedula' => '0202022653',
                'nombres' => 'KATTY ELIZABETH',
                'apellidos' => 'YÁNEZ VELASCO',
                'email' => 'katty.yanez@libertador.edu.ec',
                'telefono' => '0987654349',
                'titulo_profesional' => 'LICENCIADA EN CIENCIAS DE LA EDUCACION MENCION INGLÉS',
                'grado_ocupacional' => 'SP3',
                'modalidad_trabajo' => 'MT',
                'fecha_vinculacion' => '2023-01-02',
                'activo' => true,
            ],
            [
                'cedula' => '0202093571',
                'nombres' => 'MYRELLA ALEJANDRA',
                'apellidos' => 'ANGULO FUENTES',
                'email' => 'myrella.angulo@libertador.edu.ec',
                'telefono' => '0987654350',
                'titulo_profesional' => 'INGENIERA EN CONTABILIDAD Y AUDITORIA CP, MAGISTER EN PEDAGOGIA MENCIÓN EN DOCENCIA E INNOVACION EDUCATIVA',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2024-01-11',
                'activo' => true,
            ],
            [
                'cedula' => '0201538338',
                'nombres' => 'CARLOS WILFRIDO',
                'apellidos' => 'AYME AYME',
                'email' => 'carlos.ayme@libertador.edu.ec',
                'telefono' => '0987654351',
                'titulo_profesional' => 'LICENCIADO/A EN CIENCIAS DE LA EDUCACION BASICA, TECNOLOGO EN AGROPECUARIA',
                'grado_ocupacional' => 'SP3',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2014-01-11',
                'activo' => true,
            ],
            [
                'cedula' => '0201573649',
                'nombres' => 'SEGUNDO LUCAS',
                'apellidos' => 'CHIMBO CAIZA',
                'email' => 'segundo.chimbo@libertador.edu.ec',
                'telefono' => '0987654352',
                'titulo_profesional' => 'TECNÓLOGO EN AGROPECUARIA, INGENIERO EN ADMINISTRACION DE EMPRESAS Y NEGOCIOS, MAGÍSTER EN ADMINISTRACION DE LAS ORGANIZACIONES DE LA ECONOMÍA SOCIAL Y SOLIDARIA',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2014-01-11',
                'activo' => true,
            ],
            [
                'cedula' => '0201856200',
                'nombres' => 'MARCELA VERONICA',
                'apellidos' => 'CORRO VELOZ',
                'email' => 'marcela.corro@libertador.edu.ec',
                'telefono' => '0987654353',
                'titulo_profesional' => 'INGENIERA EN CONTABILIDAD Y AUDITORIA CP, MAGISTER EN EDUCACIÓN BASICA',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2017-01-06',
                'activo' => true,
            ],
            [
                'cedula' => '1722194600',
                'nombres' => 'PABLO ANDRES',
                'apellidos' => 'DOMINGUEZ SALAZAR',
                'email' => 'pablo.dominguez@libertador.edu.ec',
                'telefono' => '0987654354',
                'titulo_profesional' => 'INGENIERO COMERCIAL',
                'grado_ocupacional' => 'SP3',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2024-01-08',
                'activo' => true,
            ],
            [
                'cedula' => '0201813789',
                'nombres' => 'EVELIN SHAJAIRA',
                'apellidos' => 'ERAZO BENAVIDES',
                'email' => 'evelin.erazo@libertador.edu.ec',
                'telefono' => '0987654355',
                'titulo_profesional' => 'MAGISTER EN GESTION DEL TALENTO HUMANO, LICENCIADA EN CIENCIAS DE LA EDUCACION MENCION EDUCACION BASICA, INGENIERA EN ADMINISTRACION DE EMPRESAS Y NEGOCIOS',
                'grado_ocupacional' => 'SP3',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2022-01-07',
                'activo' => true,
            ],
            [
                'cedula' => '0201380565',
                'nombres' => 'VERONICA VANESSA',
                'apellidos' => 'ESPINOZA ABRIL',
                'email' => 'veronica.espinoza@libertador.edu.ec',
                'telefono' => '0987654356',
                'titulo_profesional' => 'INGENIERA EN CONTABILIDAD Y AUDITORIA CP, LICENCIADA EN INFORMATICA EDUCATIVA',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2022-01-06',
                'activo' => true,
            ],
            [
                'cedula' => '1710642826',
                'nombres' => 'OLGA ANGELICA',
                'apellidos' => 'GAVILEMA VISTIN',
                'email' => 'olga.gavilema@libertador.edu.ec',
                'telefono' => '0987654357',
                'titulo_profesional' => 'LICENCIADA EN CONTABILIDAD Y AUDITORIA, MAGISTER EN GERENCIA EMPRESARIAL',
                'grado_ocupacional' => 'SP2',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2024-01-05',
                'activo' => true,
            ],
            [
                'cedula' => '1804163333',
                'nombres' => 'AMPARO RAQUEL',
                'apellidos' => 'LOPEZ BONILLA',
                'email' => 'amparo.lopez@libertador.edu.ec',
                'telefono' => '0987654358',
                'titulo_profesional' => 'LICENCIADA EN CONTABILIDAD Y AUDITORIA CP, MAGISTER EN EDUCACIÓN INNOVACIÓN Y LIDERAZGO EDUCATIVO',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2021-01-12',
                'activo' => true,
            ],
            [
                'cedula' => '0201240389',
                'nombres' => 'LUIS ALFREDO',
                'apellidos' => 'LUCINTUÑA PUNINA',
                'email' => 'luis.lucintuña@libertador.edu.ec',
                'telefono' => '0987654359',
                'titulo_profesional' => 'LICENCIADO EN CONTABILIDAD Y AUDITORIA CONTADOR PUBLICO AUDITOR, LICENCIADO EN CIENCIAS DE LA EDUCACION MENCION EDUCACION BASICA INTERCULTURAL BILINGUE',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'MT',
                'fecha_vinculacion' => '2015-01-03',
                'activo' => true,
            ],
            [
                'cedula' => '0202154746',
                'nombres' => 'VERONICA ELIZABETH',
                'apellidos' => 'QUINTANA BARRAGAN',
                'email' => 'veronica.quintana@libertador.edu.ec',
                'telefono' => '0987654360',
                'titulo_profesional' => 'MAGISTER EN GESTION EDUCATIVA MENCIÓN EN ORGANIZACION, DIRECCION E INNOVACION DE LOS CENTROS EDUCATIVOS, INGENIERA ADMINISTRACIÓN DE EMPRESAS',
                'grado_ocupacional' => 'SP2',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2022-01-05',
                'activo' => true,
            ],
            [
                'cedula' => '0201819588',
                'nombres' => 'ELIZABETH ALEXANDRA',
                'apellidos' => 'SAYAY ORTIZ',
                'email' => 'elizabeth.sayay@libertador.edu.ec',
                'telefono' => '0987654361',
                'titulo_profesional' => 'LIC. CONTABILIDAD Y AUDITORIA, MÁSTER UNIVERSITARIO EN AUDITORÍAS DE CUENTAS',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2023-01-11',
                'activo' => true,
            ],
            [
                'cedula' => '0201849445',
                'nombres' => 'ANITA KARINA',
                'apellidos' => 'SERRANO CASTRO',
                'email' => 'anita.serrano@libertador.edu.ec',
                'telefono' => '0987654362',
                'titulo_profesional' => 'LCDA. EN CIENCIAS DE LA EDUCACION MENCION INFORMATICA EDUCATIVA, MAGISTER EN GERENCIA EDUCATIVA, ESPECIALISTA EN GESTION EDUCATIVA, MAGISTER EN GESTION DE RIESGOS Y DESASTRES, LICENCIADA EN CIENCIAS DE LA EDUCACION, INGENIERA EN MARKETING',
                'grado_ocupacional' => 'SP8',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2023-09-19',
                'activo' => true,
            ],
            [
                'cedula' => '2200227581',
                'nombres' => 'SUSANA CAROLINA',
                'apellidos' => 'LEDESMA TRUJILLO',
                'email' => 'susana.ledesma@libertador.edu.ec',
                'telefono' => '0987654363',
                'titulo_profesional' => 'LCDA. EN CIENCIAS DE LA EDUCACION MENCION EDUCACIÒN BÀSICA, MÀSTER UNIVERSITARIO EN PSICOPEDAGOGÌA',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2023-03-04',
                'activo' => true,
            ],
            [
                'cedula' => '0201260438',
                'nombres' => 'SANDRA EDITH',
                'apellidos' => 'NARANJO ARGUELLO',
                'email' => 'sandra.naranjo@libertador.edu.ec',
                'telefono' => '0987654364',
                'titulo_profesional' => 'LCDA. EN CIENCIAS DE LA EDUCACION CON MENCION EN PARVULARIA, MÀSTER UNIVERSITARIO EN PSICOPEDAGOGÌA',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2016-11-01',
                'activo' => true,
            ],
            [
                'cedula' => '1804025763',
                'nombres' => 'ALEX FABIAN',
                'apellidos' => 'MORA VALLEJO',
                'email' => 'alex.mora@libertador.edu.ec',
                'telefono' => '0987654365',
                'titulo_profesional' => 'INGENIERO AUTOMOTRIZ',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2016-03-10',
                'activo' => true,
            ],
            [
                'cedula' => '0201750114',
                'nombres' => 'JUAN PABLO',
                'apellidos' => 'POMA LOJANO',
                'email' => 'juan.poma@libertador.edu.ec',
                'telefono' => '0987654366',
                'titulo_profesional' => 'MAGISTER EN ECOEFICIENCIA INDUSTRIAL MENCIÓN EFICIENCIA ENERGÉTICA, INGENIERO EN ADMINISTRACIÓN Y PRODUCCIÓN INDUSTRIAL, TECNÓLOGO EN ELECTRÓNICA, LICENCIADO EN CIENCIAS DE LA EDUCACIÓN MENCIÓN INFORMÁTICA EDUCATIVA',
                'grado_ocupacional' => 'SP2',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2018-01-07',
                'activo' => true,
            ],
            [
                'cedula' => '0201859774',
                'nombres' => 'KAROLINA LIZBETH',
                'apellidos' => 'PANATA HERNANDEZ',
                'email' => 'karolina.panata@libertador.edu.ec',
                'telefono' => '0987654367',
                'titulo_profesional' => 'INGENIERO EN ELECTRÓNICA Y TELECOMUNICACIONES',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2024-01-12',
                'activo' => true,
            ],
            [
                'cedula' => '0503094864',
                'nombres' => 'PAUL ALFREDO',
                'apellidos' => 'LEMA OSORIO',
                'email' => 'paul.lema@libertador.edu.ec',
                'telefono' => '0987654368',
                'titulo_profesional' => 'INGENIERO ELÉCTRICO EN SISTEMAS ELÉCTRICOS DE POTENCIA, INGENIERO EN FINANZAS, CONTADOR PÚBLICO - AUDITOR, INGENIERO EN ELECTROMECÁNICA',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2022-01-05',
                'activo' => true,
            ],
            [
                'cedula' => '0201886983',
                'nombres' => 'WASHINGTON EDUARDO',
                'apellidos' => 'GUASTAY CAJO',
                'email' => 'washington.guastay@libertador.edu.ec',
                'telefono' => '0987654369',
                'titulo_profesional' => 'MAGISTER EN ECOEFICIENCIA INDUSTRIAL MENCIÓN EFICIENCIA ENERGÉTICA, INGENIERO EN ADMINISTRACIÓN Y PRODUCCIÓN INDUSTRIAL, TECNÓLOGO EN ELECTRICIDAD',
                'grado_ocupacional' => 'SP4',
                'modalidad_trabajo' => 'TC',
                'fecha_vinculacion' => '2018-01-07',
                'activo' => true,
            ],
        ];

        foreach ($docentes as $docenteData) {
            // Crear usuario en la tabla users
            $user = User::create([
                'cedula' => $docenteData['cedula'],
                'nombres' => $docenteData['nombres'],
                'apellidos' => $docenteData['apellidos'],
                'email' => $docenteData['email'],
                'password' => Hash::make($docenteData['cedula']),
                'tipo_usuario' => 'docente',
                'telefono' => $docenteData['telefono'],
                'activo' => true,
            ]);

            // Asignar rol de docente
            $user->assignRole('docente');

            // Crear registro en la tabla docentes
            Docente::create([
                'user_id' => $user->id,
                'titulo_profesional' => $docenteData['titulo_profesional'],
                'grado_ocupacional' => $docenteData['grado_ocupacional'],
                'modalidad_trabajo' => $docenteData['modalidad_trabajo'],
                'fecha_vinculacion' => $docenteData['fecha_vinculacion'],
                'activo' => $docenteData['activo'],
            ]);
        }
    }
}
